name: basic

on: push

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Basic script
      run: |
        ls
        javac main.java
        java main.java
